apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kubeserve
spec:
  replicas: 3
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
        - name: kubeserve-cont
          image: leaddevops/kubeserve:v1 
---
apiVersion: v1
kind: Service
metadata:
  name: kubeservesvc
spec:
  type: NodePort
  selector:
    app: kubeserve
  ports:
    - port: 80
      targetPort: 80


