apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      name: portfolio-website
      labels:
        app: portfolio-website
    spec:
      containers:
        - name: portfolio-website-cont
          image: azamsajjad/portfolio:deployed
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-svc
  labels:
    app: portfolio-website
spec:
  selector: 
      app: portfolio-website
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

