apiVersion: v1
kind: Pod
metadata: 
  name: labels-envar
  labels:
    purpose: demonstrate-errors
spec:
  containers:
    - name: envar-container
      image: gcr.io/google-samples/node-hello:1.0
      env:
        - name: WELCOME
          value: "Hello from the environment"
        - name: CKAEXAM
          value: "CKA exam version 1.18"


            # kubectl exec -it labels-envar -- /bin/bash
            # printenv
