apiVersion: v1
kind: Pod
metadata:
  name: init-container-nginx
spec: 
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html
    # this container will run initially and will provide custom html input
  initContainers:
    - name: alpine
      image: alpine
      command:
        - sh
        - "-c"
        - |
          mkdir -p /init-cont && \
          touch "/init-cont/index.html" && \
          echo "init Cont Demo Works Dear !!" > "/init-cont/index.html"
          sleep 30
      volumeMounts:
        - name: myvol
          mountPath: "/init-cont"
  volumes:
    - name: myvol
      emptyDir: {}



