apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kubeserve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      tolerations:
        - key: color
          operator: "Equals"
          value: red
          effect: "NoSchedule"
      containers:
        - name: kubeserve-cont
          image: lerndevops/kubeserve:v1
          

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kubeserve 
# spec:
#   replicas: 5
#   selector:
#     matchlabels:
#       app: kubeserve
#   template:
#     metadata:
#       name: kubeserve 
#       labels:
#         app: kubeserve
#     spec:
#       tolerations:
#         - key: env
#           operator: "Exists"
#           effect: "NoExecute"
#         - key: person
#           operator: "Equal"
#           value: police
#           effect: "NoSchedule"
          
#         - operators: Exists,Equal
#         - effects: NoExecute,NoSchedule,PreferNoSchedule