apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: user1-role
rules:
  - apiGroups: ['*']
    resources: ['pods','deployments','replicasets']
    verbs: ['get','list','watch','create','update']
