apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  db: mongodb
  app: myapp

--- 
apiVersion: v1
kind: Pod 
metadata:
  name: config-pod
spec:
  containers:
  - image: nginx
    name: config-pod-cont
    command: ['/bin/sh', '-c', 'echo $(KEY1) $(KEY2)' ]
    env:
      - name: KEY1
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: db
      - name: KEY2
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: app
  restartPolicy: Never

