apiVersion: v1
kind: Secret 
metadata:
  name: userpass
data:
  username: bXktYXBw
  password: cGFzc3dvcmQ=

--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: secret-pod
spec: 
  containers:
    - image: nginx
      name: secret-pod-cont
      volumeMounts:
        - name: secret-vol
          mountPath: /etc/secret
          readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: userpass