apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
spec:
  containers:
  - image: tomcat
    name: my-pvc-pod-container
    volumeMounts:
    - name: pv
      mountPath: "/usr/local/tomcat/logs"
  
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: my-pvc