apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle 
  capacity: 
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/e/pvdata